chore: add "electron-builder-squirrel-windows" for windows

diff --git a/.github/workflows/push-to-publish.yml b/.github/workflows/push-to-publish.yml
--- a/.github/workflows/push-to-publish.yml
+++ b/.github/workflows/push-to-publish.yml
@@ -84,6 +84,17 @@ jobs:
       env: # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsenv
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+    - name: Move artifacts
+      if: matrix.os != 'windows-latest'
+      run: |
+        mkdir artifact
+        mv "release/(*.deb,*.AppImage,*.dmg)" artifact || true
+    - name: Upload artifacts
+      uses: actions/upload-artifact@v1
+      with:
+        name: ${{matrix.os}}
+        path: artifact
+
   build-win:
     name: Build & Publish (Windows)
     runs-on: ${{ matrix.os }}
@@ -119,7 +130,7 @@ jobs:
 
     - name: (win) yarn global install if necessary
       run: |
-        yarn global add electron-builder
+        yarn global add electron-builder electron-builder-squirrel-windows
 
     # Couldn't make it work on Windows
     # - name: Append "yarn global bin directory" to PATH
@@ -148,10 +159,20 @@ jobs:
         ${{ steps.yarn-global-bin.outputs.dir }}/electron-builder build --publish always
       env: # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsenv
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    - name: Cleanup meta files # Reference https://gist.github.com/azu/673426500458f63f019c8f5e013f282a
+
+    - name: (win) Move artifacts
       run: |
-        npx rimraf "release/!(*.exe|*.deb|*.AppImage|*.dmg)"
-    - uses: actions/upload-artifact@v1
+        mkdir artifact
+        mv release/*.exe artifact
+    - name: Upload artifacts
+      uses: actions/upload-artifact@v1
       with:
-        name: my-artifact
-        path: release
+        name: ${{matrix.os}}
+        path: artifact
+    # - name: Cleanup meta files # Reference https://gist.github.com/azu/673426500458f63f019c8f5e013f282a
+    #   run: |
+    #     npx rimraf "release/!(*.exe|*.deb|*.AppImage|*.dmg)"
+    # - uses: actions/upload-artifact@v1
+    #   with:
+    #     name: my-artifact
+    #     path: artifact
